### ISSUE TITLE
Не корректное отображение времени платежа

### ISSUE THREAD

**Issue by infimpossible** [kotleni/moneytracker-ios#13]
Устройство: iPhone 7 (iOS 15.0)
Проблема: Время создания платежа отображается не корректно.

![2022-08-09 10 20 55](https://user-images.githubusercontent.com/110890339/183589322-9afffc24-f430-4bce-b79b-3081087a38eb.jpg)

**Comment by kotleni** [comment]
Fixed: 45727c39e32ff36c3174766e9a45bbae0d2f82c1
